// <auto-generated />
using System;
using EventService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EventService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EventDbContext))]
    [Migration("20260906201939_AddOutboxAndDropMassTransit")]
    partial class AddOutboxAndDropMassTransit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("events")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EventService.Domain.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<DateTimeOffset>("DateRecordCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_record_creation");

                    b.Property<DateTimeOffset?>("DateRecordEdit")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_record_edit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserRecordCreation")
                        .HasColumnType("uuid")
                        .HasColumnName("user_record_creation");

                    b.Property<Guid?>("UserRecordEdit")
                        .HasColumnType("uuid")
                        .HasColumnName("user_record_edit");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("venue");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_events_date");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("IX_events_owner_id");

                    b.ToTable("events", "events");
                });

            modelBuilder.Entity("EventService.Domain.Entities.Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<DateTimeOffset>("DateRecordCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_record_creation");

                    b.Property<DateTimeOffset?>("DateRecordEdit")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_record_edit");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<Guid>("UserRecordCreation")
                        .HasColumnType("uuid")
                        .HasColumnName("user_record_creation");

                    b.Property<Guid?>("UserRecordEdit")
                        .HasColumnType("uuid")
                        .HasColumnName("user_record_edit");

                    b.HasKey("Id")
                        .HasName("pk_zones");

                    b.HasIndex("EventId")
                        .HasDatabaseName("IX_zones_event_id");

                    b.ToTable("zones", "events", t =>
                        {
                            t.HasCheckConstraint("CK_zones_price_positive", "\"price\" > 0");
                        });
                });

            modelBuilder.Entity("EventService.Infrastructure.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("DateRecordCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_record_creation");

                    b.Property<DateTimeOffset?>("DateRecordEdit")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_record_edit");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("last_error");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("message_type");

                    b.Property<DateTimeOffset>("NextTryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_try_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TopicArn")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("topic_arn");

                    b.Property<Guid>("UserRecordCreation")
                        .HasColumnType("uuid")
                        .HasColumnName("user_record_creation");

                    b.Property<Guid?>("UserRecordEdit")
                        .HasColumnType("uuid")
                        .HasColumnName("user_record_edit");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_outbox_messages_correlation_id");

                    b.HasIndex("MessageId")
                        .IsUnique()
                        .HasDatabaseName("UX_outbox_messages_message_id");

                    b.HasIndex("Status", "NextTryAt")
                        .HasDatabaseName("IX_outbox_messages_status_next_try_at");

                    b.ToTable("outbox_messages", "events");
                });

            modelBuilder.Entity("EventService.Domain.Entities.Zone", b =>
                {
                    b.HasOne("EventService.Domain.Entities.Event", null)
                        .WithMany("Zones")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_zones_events_event_id");
                });

            modelBuilder.Entity("EventService.Domain.Entities.Event", b =>
                {
                    b.Navigation("Zones");
                });
#pragma warning restore 612, 618
        }
    }
}
