// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotificationService.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NotificationService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NotificationDbContext))]
    [Migration("20260906201951_DropMassTransitTables")]
    partial class DropMassTransitTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("notifications")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NotificationService.Domain.Entities.NotificationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("DateRecordCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_record_creation");

                    b.Property<DateTimeOffset?>("DateRecordEdit")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_record_edit");

                    b.Property<DateTimeOffset>("EventDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_date");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_name");

                    b.Property<string>("EventVenue")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("event_venue");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("MessageTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("message_timestamp");

                    b.Property<DateTimeOffset?>("NextTryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_try_at");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("payload_hash");

                    b.Property<string>("SmtpMessageId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("smtp_message_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserRecordCreation")
                        .HasColumnType("uuid")
                        .HasColumnName("user_record_creation");

                    b.Property<Guid?>("UserRecordEdit")
                        .HasColumnType("uuid")
                        .HasColumnName("user_record_edit");

                    b.Property<string>("ZoneDetailsJson")
                        .HasColumnType("text")
                        .HasColumnName("zone_details_json");

                    b.HasKey("Id")
                        .HasName("pk_notification_records");

                    b.HasIndex("CorrelationId")
                        .IsUnique()
                        .HasDatabaseName("UX_notification_records_correlation_id");

                    b.HasIndex("Status", "NextTryAt")
                        .HasDatabaseName("IX_notification_records_status_next_try_at");

                    b.ToTable("notification_records", "notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
